# Generated by Django 4.2.1 on 2023-05-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roll',
            new_name='Role',
        ),
    ]
